server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  tomcat:
    max-parameter-count: 10000
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
    max-part-header-size: 2048B

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: dev

  config:
    activate:
      on-profile: dev

  output:
    ansi:
      enabled: ALWAYS

  application:
    name: shahafa-bookshop

  datasource:
    url: jdbc:mysql://localhost:3306/BookShop?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: huyenfilw642@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    debug: true

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: xo-cua-huyen-ne
    region: ap-southeast-1
    folder: "SHAHAFA Book Store"

ghn:
  token: ${GHN_TOKEN}
  shop-id: ${GHN_SHOP_ID}
  base-url: https://dev-online-gateway.ghn.vn


admin: { email_default: "admin@test.com", password_default: "00000000" }
customer-account-test: { email: "customer@test.com", password: "00000000" }
manager-account-test: { email: "manager@test.com", password: "00000000" }

logging:
  level:
    org.springframework.security: DEBUG

#payos:
#  client-id: YOUR_PAYOS_CLIENT_ID
#  api-key: YOUR_PAYOS_API_KEY
#  checksum-key: YOUR_PAYOS_CHECKSUM_KEY
